/* Curated Star-Eyed Charms deck. `sourceOriginal` preserves the canonical source mapping. */
window.GOBLIN_DECK = [
  { number: '0', title: 'The Fool on Wheels', keywords: 'momentum, curiosity', upright: 'Begin before the route agrees with you.', reversed: 'Your wheels need a pause before another prophecy.', source: 'assets/10-roller-skating-caterpillar.png', sourceOriginal: '03_OUTPUT/posters/cosmic-acid/star-eyed-charms-series/10-roller-skating-caterpillar.png', artAlt: 'Roller-skating caterpillar charm.' },
  { number: 'I', title: 'The Melting Magician', keywords: 'spark, making', upright: 'One small spell is enough to start.', reversed: 'Stop burning yourself to illuminate everyone else.', source: 'assets/24-candle-headed-goblin-wizard.png', sourceOriginal: '03_OUTPUT/posters/cosmic-acid/star-eyed-charms-series/24-candle-headed-goblin-wizard.png', artAlt: 'Candle-headed goblin wizard charm.' },
  { number: 'II', title: 'The High Priest of Tea', keywords: 'rest, intuition', upright: 'Sit still long enough to hear the kettle’s opinion.', reversed: 'You have steeped in the same thought long enough.', source: 'assets/03-frog-in-teacup.png', sourceOriginal: '03_OUTPUT/posters/cosmic-acid/star-eyed-charms-series/03-frog-in-teacup.png', artAlt: 'Frog sitting in a teacup charm.' },
  { number: 'III', title: 'The Snail With Air Miles', keywords: 'pace, contradiction', upright: 'Slow progress may still have wings.', reversed: 'Someone else’s urgency has crawled into your shell.', source: 'assets/28-winged-third-eye-snail-cat.png', sourceOriginal: '03_OUTPUT/posters/cosmic-acid/star-eyed-charms-series/28-winged-third-eye-snail-cat.png', artAlt: 'Winged third-eye snail-cat charm.' },
  { number: 'IV', title: 'The Weather in Custody', keywords: 'containment, feelings', upright: 'Give the storm a vessel and a little room.', reversed: 'The cork is doing too much emotional labour.', source: 'assets/16-storm-in-a-bottle.png', sourceOriginal: '03_OUTPUT/posters/cosmic-acid/star-eyed-charms-series/16-storm-in-a-bottle.png', artAlt: 'Storm contained in a bottle charm.' },
  { number: 'V', title: 'The Late Eternity', keywords: 'timing, patience', upright: 'Let the useful thing take its own time.', reversed: 'Waiting has quietly become your whole plan.', source: 'assets/20-cosmic-hourglass.png', sourceOriginal: '03_OUTPUT/posters/cosmic-acid/star-eyed-charms-series/20-cosmic-hourglass.png', artAlt: 'Cosmic hourglass charm.' },
  { number: 'VI', title: 'The Door With Opinions', keywords: 'threshold, choice', upright: 'Step through the opening that already exists.', reversed: 'An open door is still allowed to be the wrong door.', source: 'assets/45-stone-archway-galaxy-portal.png', sourceOriginal: '03_OUTPUT/posters/cosmic-acid/star-eyed-charms-series/45-stone-archway-galaxy-portal.png', artAlt: 'Stone archway galaxy portal charm.' },
  { number: 'VII', title: 'The Forecast Has Teeth', keywords: 'disruption, clarity', upright: 'A little thunder may finally clear the air.', reversed: 'Every cloud has started sounding like an emergency.', source: 'assets/46-many-eyed-storm-cloud-lightning.png', sourceOriginal: '03_OUTPUT/posters/cosmic-acid/star-eyed-charms-series/46-many-eyed-storm-cloud-lightning.png', artAlt: 'Many-eyed storm cloud with lightning charm.' },
  { number: 'VIII', title: 'The Village That Sprouted', keywords: 'belonging, support', upright: 'Let your strange little community help.', reversed: 'You may leave the village meeting before becoming its roof.', source: 'assets/47-mushroom-village-waterfall.png', sourceOriginal: '03_OUTPUT/posters/cosmic-acid/star-eyed-charms-series/47-mushroom-village-waterfall.png', artAlt: 'Mushroom village and waterfall charm.' },
  { number: 'IX', title: 'The Fork of Questionable Destiny', keywords: 'direction, resolve', upright: 'Choose one prong and make a clean move.', reversed: 'Three competing missions are still three missions.', source: 'assets/53-eyed-wrench-tool-charm.png', sourceOriginal: '03_OUTPUT/posters/cosmic-acid/star-eyed-charms-series/53-eyed-wrench-tool-charm.png', artAlt: 'Winged three-pronged trident charm.' },
  { number: 'X', title: 'The Key to Absolutely Somewhere', keywords: 'possibility, access', upright: 'Try the small opening before forcing the wall.', reversed: 'Possessing a key does not make every lock your responsibility.', source: 'assets/58-eyed-skeleton-key-charm.png', sourceOriginal: '03_OUTPUT/posters/cosmic-acid/star-eyed-charms-series/58-eyed-skeleton-key-charm.png', artAlt: 'Eyed skeleton key charm.' },
  { number: 'XI', title: 'The Stapler of Binding Consequences', keywords: 'commitment, structure', upright: 'Fasten one useful thing to another.', reversed: 'Check what you have accidentally stapled yourself to.', source: 'assets/65-eyed-stapler-charm.png', sourceOriginal: '03_OUTPUT/posters/cosmic-acid/star-eyed-charms-series/65-eyed-stapler-charm.png', artAlt: 'Eyed stapler charm.' }
];
